"""
#4
12 marks

You have for download the next files:
2 csv, 2 jpg, 1 png and 3 pdf files.

Complete the make_a_folder_of function. 
Your function will receive as input one string which is one of the following specific 
file extension (".csv", ".pdf", ".png" or ".jpg") and will 
move the files of that type into that folder.

The input is a single file type. 
Your function will return a set of the names of the files in that new folder

example input:  ".pdf"
example output: {'shoping_list.pdf', 'travels.pdf', 'test.pdf'}

example input:  ".csv"
example output: {'SampleCSVFile_2kb.csv', 'SampleCSVFile_11kb.csv'}

Hints: you can look into the Path.mkdir() function to create folders, 
the iterdir() function to iterate over a folder. 
You can move files using, the shutil function or the Path.rename / Path.replace functions

Note: You only have to upload the third_assignment.py file into the Autolab page. All the other files are 
already available in the grader. I put them for you to download to be able to practice with the files and try different
cases before submitting your solution. You might be tempted to just include the file names into a set, but I will 
personally check that your script is making the proper folder structure. If the folders are not being generated by 
extension you will not have any marks in this exercise

"""
from pathlib import Path,PurePath
import shutil
def make_a_folder_of(folder):
    output=set()
    pwd=Path.cwd()
    pdf=sorted(Path(pwd).glob('*pdf'))
    png=sorted(Path(pwd).glob('*png'))
    jpg=sorted(Path(pwd).glob('*jpg'))
    csv=sorted(Path(pwd).glob('*csv'))
    Path.mkdir(pwd/folder)
    
    for files in pwd.iterdir():
        if folder == ".pdf":
            for pd in pdf:
                shutil.move(pd,pwd/folder/pd)
                output.add(pd.name)
            break
               
        elif folder == ".png":
            for pn in png:
                shutil.move(pn,pwd/folder/pn)
                output.add(pn.name) 
            break
                        
        elif folder == ".jpg":
            for jg in jpg:
                shutil.move(jg,pwd/folder/jg)
                output.add(jg.name)
            break
               
           
        elif folder == ".csv":
            for cs in csv:
                shutil.move(cs,pwd/folder/cs)
                output.add(cs.name)
            break
        
        else:
            return 0        
   
    return output